export const SHOW_OPTION_WINDOW = 'SHOW_OPTION_WINDOW';
export const SHOW_CHANNEL_WINDOW = 'SHOW_CHANNEL_WINDOW';
export const DELETE_CHANNEL_WINDOW = 'DELETE_CHANNEL_WINDOW';
export const CREATE_CHANNEL = 'CREATE_CHANNEL';